
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern_frontend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern_backend
    ports:
      - "8080:8080"
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
